language: scala

scala:
  - 2.9.3

jdk:
  - oraclejdk7

sudo: false

before_install:
  - openssl aes-256-cbc -pass pass:$PGP_PASSPHRASE -in secret.asc.enc -out local.secret.asc -d
  - openssl aes-256-cbc -pass pass:$PGP_PASSPHRASE -in public.asc.enc -out local.public.asc -d

script: "sbt test"

deploy:
  skip_cleanup: true
  provider: script
  script: sbt publishSigned sonatypeRelease
  on:
    tags: true

env:
  global:
    - secure: "Km7zfQR5Q4auR1tWeVNLrdTgRcwCxndszN81LIIlrYiL9t7dh3rL/CzmT+N433grNB6Y6yZgRHiLCF3mhRjZk0rjDxvhrQ+1r1PRJZOSlKXre2PQSTq+xAGkeUpKAJKtbRKQ5nCwyNyOlniHnbkck6XIKklESkMCntA4g/Fn4Dw="
    - secure: "GGrBEUcd+kuchKaGAP7LLZ/ZshtNKRuNWwOZZBxNduSRq4Q3t2eTrRhyjgO+wmfsni5SLNA/tpqvdrjU0FQGtO/UrUd+OweFJ4JQ1niTJbYuewEWRGXpXybo7HV3jeWMQt7RkJIYqOUwCNHZnSMV0xJNEyIXrX9XSVwfyNZpDDA="
